// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/traPtitech/Checkin-Server/repository/gorm"
	"github.com/traPtitech/Checkin-Server/router"
	"go.uber.org/zap"
)

// Injectors from wire.go:

// InitializeApp sets up the application with all its dependencies
func InitializeApp() (*App, error) {
	logger, err := provideLogger()
	if err != nil {
		return nil, err
	}
	repository, err := gorm.NewRepository(logger)
	if err != nil {
		return nil, err
	}
	handlers := router.NewHandlers(logger, repository)
	app := NewApp(logger, handlers)
	return app, nil
}

// wire.go:

// provideLogger creates a zap logger
func provideLogger() (*zap.Logger, error) {
	logger, err := zap.NewProduction()
	if err != nil {
		return nil, err
	}
	return logger, nil
}
