// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"
)

type User struct {
	ID               string
	MailHash         string
	StripeCustomerID string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}
