// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, mail_hash, stripe_customer_id) VALUES (?, ?, ?)
`

type CreateUserParams struct {
	ID               string
	MailHash         string
	StripeCustomerID string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.ID, arg.MailHash, arg.StripeCustomerID)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, mail_hash, stripe_customer_id, created_at, updated_at FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.MailHash,
		&i.StripeCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByMailHash = `-- name: GetUserByMailHash :one
SELECT id, mail_hash, stripe_customer_id, created_at, updated_at FROM users WHERE mail_hash = ? LIMIT 1
`

func (q *Queries) GetUserByMailHash(ctx context.Context, mailHash string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByMailHash, mailHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.MailHash,
		&i.StripeCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStripeCustomerId = `-- name: UpdateUserStripeCustomerId :exec
UPDATE users SET stripe_customer_id = ? WHERE id = ?
`

type UpdateUserStripeCustomerIdParams struct {
	StripeCustomerID string
	ID               string
}

func (q *Queries) UpdateUserStripeCustomerId(ctx context.Context, arg UpdateUserStripeCustomerIdParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStripeCustomerId, arg.StripeCustomerID, arg.ID)
	return err
}
